#! /QOpenSys/pkgs/bin/bash

if [ $# -lt 2 ]; then
  echo 1>&2 "$0: not enough arguments"
  echo 1>&2 "Usage: launch path_to_joblog_json command"
  exit 2
elif [ $# -gt 2 ]; then
  echo 1>&2 "$0: too many arguments"
  echo 1>&2 "Usage: launch path_to_joblog_json command"
  exit 2
fi

joblog_json=$1
cmd=$2
temp_json1=$(mktemp)
temp_json2=$(mktemp)

if [ ! -f $joblog_json ]; then
    echo "[]" > $joblog_json
fi

pid=$$
pipe="/tmp/pipe$pid"
mkfifo "$pipe"

getjobid -s > "$pipe"
jobid=$(cat < "$pipe")
rm -rf "$pipe"

cl "CHGJOB LOG(4 00 *SECLVL)" 

timestamp=$(date +"%Y-%m-%d-%H.%M.%S.%N")

cl "$cmd"
db2util -o json "SELECT MESSAGE_ID,MESSAGE_TEXT,MESSAGE_SECOND_LEVEL_TEXT,MESSAGE_TYPE,SEVERITY,MESSAGE_TIMESTAMP FROM TABLE(QSYS2.JOBLOG_INFO('${jobid}')) A" | \
jq -c "{cmd:\"${cmd}\", cmd_time:\"${timestamp}\",msgs:[.records[] | select(.MESSAGE_TEXT | contains(\"not safe for a multithreaded job.\") | not | {msgid:.MESSAGE_ID, type:.MESSAGE_TYPE, severity:.SEVERITY,message_time:.MESSAGE_TIMESTAMP,message_text:.MESSAGE_TEXT, second_level:.MESSAGE_SECOND_LEVEL_TEXT}]}" > $temp_json1
(jq -c '. += $temp' $joblog_json --slurpfile temp $temp_json1) > $temp_json2
mv $temp_json2 $joblog_json

rm -rf $temp_json1 $temp_json2