#!/usr/bin/bash
if [[ ! -e /QSYS.LIB/${2}.LIB/${1} ]]; then
   echo "Build not successful for ${2}/${1}"
   if [[ -e /QSYS.LIB/QTEMP.LIB/${1} ]]; then
      mv /QSYS.LIB/QTEMP.LIB/${1} /QSYS.LIB/${2}.LIB
   fi
else
   echo "Build successful for ${2}/${1}"
   if [[ -e /QSYS.LIB/QTEMP.LIB/${1} ]]; then
      rm -f /QSYS.LIB/QTEMP.LIB/${1}
   fi
fi
exit $?