#!/usr/bin/env bash

SCRIPT_DIR="$(dirname "$0")"
BOB_DIR=$(realpath "${SCRIPT_DIR}/../..")

PYTHONPATH="${BOB_DIR}/src":${PYTHONPATH} /QOpenSys/pkgs/bin/python3.9 "${BOB_DIR}/src/makei/crtfrmstmf.py" "$@"
