#!/usr/bin/env bash

source=$1 # qualified path
object=$2 # unqualified path
objpath=$3

objectBasename=${object%.*}

sourceBasename=${source##*/} # removes the path
sourceBasename=${sourceBasename%.*} #removes the extension
sourceSuffix=${source##*.}

ICONV="/QOpenSys/usr/bin/iconv"
ICONV_EBCDIC="IBM-037"
ICONV_ASCII="UTF-8"

if [ "$sourceSuffix" = 'PRTF' ]; then SLTFLD='*OUTPUT'; else SLTFLD='*BOTH *KEY'; fi; 
system -v "GENCSRC OBJ('"$objpath"/"$object"') SRCSTMF('"$source".TH') SLTFLD($SLTFLD) TYPEDEFPFX('"$objectBasename"')"
(file="$sourceBasename"_"$sourceSuffix"_H; echo "#ifndef ${file}"; echo "   #define ${file}"; "$ICONV" -f "$ICONV_EBCDIC" -t "$ICONV_ASCII" "$source".TH | tr -d '\r' | sed -e '/^ *int/ s/;     /;/' -e '/^ *int/ s/int/long int/'; echo "#endif  /* ${file} */") > "$source".H1
rm "$source".TH
if [ -f ""$source".H" ]; then sed -e '/^\/\//d' "$source".H >"$source".H-old; fi
sed -e '/^\/\//d' "$source".H1 >"$source".H-new
if ! cmp "$source".H-new "$source".H-old >/dev/null 2>&1; then mv -f "$source".H1 "$source".H; echo "*** Created new typedef file "$source".H for file ["$object"]"; fi
if [ -f ""$source".H-old" ]; then rm ""$source".H-old"; fi
if [ -f ""$source".H-new" ]; then rm ""$source".H-new"; fi
if [ -f ""$source".H1" ]; then rm ""$source".H1"; fi