#!/usr/bin/env bash
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)

joblog_json=$1
pseudoSrcFile=$2
objlib=$3
objname=$4
precmd=$5
postcmd=$6
object=$7
source=$8
output=$9
cmd=""
suppressError=""

while read -r line; do
  line=$(echo "$line" | sed 's/\r//')
  # if a line begins with ! then suppress errors and continue
  if [[ $line =~ \!.* ]]; then
    line=$(echo "$line" | sed 's/^\!//')
    suppressError="Y"
  fi
  if [[ $line = '/*'* ]]; then continue; fi
  if [[ $line = '' ]]; then continue; fi
  if [[ $line =~ .*\+\S* ]]; then
    linetmp=$(echo "$line" | sed 's/\+\S*$//')
    cmd="${cmd} ${linetmp}"
    continue

  fi

  cmd+=$line
  if [ -n "$cmd" ]; then
    cmd=$(echo "$cmd" | sed "s/&O/$objlib/g" | sed "s/&N/$objname/g")
    "$SCRIPT_DIR"/launch "$joblog_json" "$cmd" "$precmd" "$postcmd" "$object" "$source" "$output" </dev/null
    if [[ $? -ne 0 && "$suppressError" != "Y" ]]; then
      echo "Command failed: $cmd"
      exit 1
    fi
    suppressError=""
    cmd=""
  fi
done < <(grep "" $pseudoSrcFile)
