#!/usr/bin/env bash

SCRIPT_DIR="$(dirname "$0")"
TOBI_DIR=$(realpath "${SCRIPT_DIR}/../..")

PYTHONPATH="${TOBI_DIR}/src":${PYTHONPATH} /QOpenSys/pkgs/bin/python3.9 "${TOBI_DIR}/src/makei/cli/get_joblog.py" "$@"
