#!/QOpenSys/pkgs/bin/bash
if [[ -e /QSYS.LIB/${2}.LIB/${1} ]]; then
   echo "Object ${2}/${1} exists"
   if [[ -e /QSYS.LIB/QTEMP.LIB/${1} ]]; then
      rm -f /QSYS.LIB/QTEMP.LIB/"${1}"
   fi
   mv -f /QSYS.LIB/"${2}".LIB/"${1}" /QSYS.LIB/QTEMP.LIB
else
   echo "Object ${2}/${1} does not exist so should build"
fi
exit $?
