#!/QOpenSys/pkgs/bin/python3.6

# Licensed Materials - Property of IBM
# 57XX-XXX
# (c) Copyright IBM Corp. 2021
""" The CLI entry for BOB"""

import argparse
import json
import os
from pathlib import Path

import sys  # nopep8
sys.path.append(str(Path(__file__).resolve().parent.parent))  # nopep8
from makei.const import BOB_PATH  # nopep8
from makei import init_project  # nopep8
from makei.build import BuildEnv  # nopep8
from makei.utils import Colors, colored, get_compile_targets_from_filenames, run_command  # nopep8


__version__ = "2.3.5"


def cli():
    """
    makei program entry
    """
    parser = argparse.ArgumentParser(prog='makei')
    subparsers = parser.add_subparsers(
        title='These are common makei commands',
        metavar='command')

    add_init_parser(subparsers)
    add_info_parser(subparsers)
    add_compile_parser(subparsers)
    add_build_parser(subparsers)
    add_cvtsrcpf_parser(subparsers)

    parser.add_argument(
        '-v', '--version',
        help="print version information and exit",
        action='store_true'
    )

    args = parser.parse_args()
    if args.version:
        print(f"Bob version {__version__}")
    elif hasattr(args, 'handle'):
        args.handle(args)
    else:
        parser.print_help()


def add_build_parser(subparsers: argparse.ArgumentParser):
    """Add subparsers for build commands"""
    build_parser = subparsers.add_parser(
        'build',
        aliases=['b'],
        help='build the whole project',
    )
    build_target_group = build_parser.add_mutually_exclusive_group()
    build_target_group.add_argument(
        '-t',
        '--target',
        help='target to be built',
        metavar='<target>'
    )
    build_target_group.add_argument(
        '-d',
        '--subdir',
        help='subdirtory to be built',
        metavar='<subdir>'
    )
    build_parser.add_argument(
        '-o',
        '--make-options',
        help='options to pass to make',
        metavar='<options>',
    )
    build_parser.add_argument(
        '--bob-path',
        help='path to the bob directory',
        metavar='<path>',
    )
    build_parser.add_argument(
        '-e',
        '--env',
        help='override environment variables',
        metavar='<var>=<value>',
        action='append'
    )
    build_parser.set_defaults(handle=handle_build)


def add_compile_parser(subparsers: argparse.ArgumentParser):
    """Add subparsers for compile commands"""
    compile_parser = subparsers.add_parser(
        'compile',
        aliases=['c'],
        help='compile a single file')
    compile_target_group = compile_parser.add_mutually_exclusive_group(
        required=True)
    compile_target_group.add_argument(
        '-f',
        '--file',
        help='file to compile',
        metavar='<filename>')
    compile_target_group.add_argument(
        '--files',
        help='files to compile, separated by colon (:)',
        metavar='<filepaths>')
    compile_parser.add_argument(
        '-o',
        '--make-options',
        help='options to pass to make',
        metavar='<options>',
    )
    compile_parser.add_argument(
        '-e',
        '--env',
        help='override environment variables',
        metavar='<var>=<value>',
        action='append'
    )
    compile_parser.add_argument(
        '--bob-path',
        help='path to the bob directory',
        metavar='<path>',
    )
    compile_parser.set_defaults(handle=handle_compile)


def add_init_parser(subparsers: argparse.ArgumentParser):
    """Add subparsers for init commands"""
    init_parser = subparsers.add_parser(
        'init',
        help='set up a new or existing project')

    init_parser.add_argument('-f', '--force',
                             help='force overwrite any existing files',
                             action='store_true')
    init_parser.set_defaults(handle=handle_init)

def add_cvtsrcpf_parser(subparsers: argparse.ArgumentParser):
    cvtsrcpf_parser = subparsers.add_parser(
        'cvtsrcpf',
        help='convert source physical file members to ASCII IFS files',
        description='Converts all members in a source physical file to properly-named \
                        (Better Object Builder-compatible), ASCII-ish, LF-terminated source files \
                        in the current directory in the IFS. An .ibmi.json will also be created at the same directory.'
    )

    cvtsrcpf_parser.add_argument(
        "file",
        help='the name of the source file',
        metavar='<file>',
    )

    cvtsrcpf_parser.add_argument(
        "library",
        help='the name of the library',
        metavar='<library>',
    )

    cvtsrcpf_parser.add_argument(
        "-c",
        help='the EBCDIC CCSID that the source in this directory should be compiled with. CCSID used to compile the source in this directory. If not specified, then the CCSID of the JOB running the build will be used.',
        metavar='<CCSID>',
        type=int,
    )
    cvtsrcpf_parser.set_defaults(handle=handle_cvtsrcpf)


def add_info_parser(subparsers: argparse.ArgumentParser):
    """Add subparsers for info commands"""
    info_parser = subparsers.add_parser(
        'info',
        help='get information about the current project')

    info_parser.set_defaults(handle=handle_info)


def handle_init(args):
    """
    Handling the init command
    """
    init_project.init_project(force=args.force)


def handle_info(_args):
    """
    Handling the info command
    """
    print("Not implemented!")


def handle_compile(args):
    """
    Processing the compile command
    """
    set_environment_vars(args)
    if args.file:
        filenames = [args.file]
    elif args.files:
        filenames = map(os.path.basename, args.files.split(':'))
    targets = get_compile_targets_from_filenames(filenames)
    build_env = BuildEnv(targets, args.make_options, get_override_vars(args))
    if build_env.make():
        exit(0)
    else:
        exit(1)

def handle_build(args):
    """
    Processing the build command
    """
    set_environment_vars(args)
    if args.target:
        target = args.target
    elif args.subdir:
        target = f"dir_{os.path.basename(args.subdir.strip(os.sep))}"
    else:
        target = "all"
    build_env = BuildEnv([target], args.make_options, get_override_vars(args))
    if build_env.make():
        exit(0)
    else:
        exit(1)

def handle_cvtsrcpf(args):
    if args.c:
        ccsid = args.c
        ccsid_flag = f" -c {args.c}"
    else:
        ccsid = None
        ccsid_flag = ""
    exit_code = run_command(f"{str(BOB_PATH / 'scripts' / 'cvtsrcpf')} {args.file} {args.library}{ccsid_flag}")
    # if exit_code == 0:
        # ibmi_json_path = Path() / ".ibmi.json"
        # if not ibmi_json_path.exists() and ccsid:
        #     data = {
        #         "build" : {
        #             "tgtCcsid" : str(ccsid)
        #         }
        #     }
        #     with ibmi_json_path.open('w') as json_file:
        #         json.dump(data, json_file, indent=4)
        #         print(colored("Created .ibmi.json at the current directory.", Colors.OKBLUE))

def get_override_vars(args):
    """ Get the override variables from the arguments"""
    if args.bob_path:
        return {"bob_path": args.bob_path}
    else:
        return {}


def set_environment_vars(args):
    """ Set the environment variables defined in the arguments"""
    if "env" in args and args.env:
        for env in args.env:
            kv_pair = env.split("=")
            if len(kv_pair) != 2:
                print(colored(f"invalid format: {env}", Colors.FAIL))
                sys.exit(1)
            key, value = kv_pair[0], kv_pair[1]
            os.environ[key] = value
            print(colored(f"Set variable <{key}> to '{value}'", Colors.OKBLUE))


if __name__ == '__main__':
    cli()
